### ISSUE TITLE
Python build doesn't work since v1.2.1

### ISSUE THREAD

**Issue by Lulu300** [cberner/raptorq#51]
Hello,

I've tried to build your module for python but it doesn't seems to work. Here's what I've tried.
```SH
lulu@Tsukuyomi:~/raptorq-1.3.0$ maturin build
💥 maturin failed
  Caused by: Couldn't find any bindings; Please specify them with --bindings/-b

lulu@Tsukuyomi:~/raptorq-1.3.0$ maturin build -b pyo3
💥 maturin failed
  Caused by: The bindings crate pyo3 was not found in the dependencies list
```
After these two fails, I've tried to generate the .so file and use it directly in python.
```SH
lulu@Tsukuyomi:~/raptorq-1.3.0$ maturin build
💥 maturin failed
  Caused by: Couldn't find any bindings; Please specify them with --bindings/-b
lulu@Tsukuyomi:~/raptorq-1.3.0$ cargo build --release
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.16
   Compiling serde v1.0.104
   Compiling quote v1.0.3
   Compiling serde_derive v1.0.104
   Compiling raptorq v1.3.0 (/home/lulu/raptorq-1.3.0)
warning: unnecessary parentheses around block return value
  --> src/matrix.rs:87:9
   |
87 |         (mask - 1)
   |         ^^^^^^^^^^ help: remove these parentheses
   |
   = note: `#[warn(unused_parens)]` on by default

    Finished release [optimized + debuginfo] target(s) in 46.88s

lulu@Tsukuyomi:~/raptorq-1.3.0$ mv target/release/libraptorq.so examples/raptorq.so
lulu@Tsukuyomi:~/raptorq-1.3.0$ cd examples/
lulu@Tsukuyomi:~/raptorq-1.3.0/examples$ python3.7 main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from raptorq import Encoder, Decoder
ImportError: dynamic module does not define module export function (PyInit_raptorq)
```
After I noticed that your module is also available on pypi, so I tried to install it.
```SH
lulu@Tsukuyomi:~/raptorq-1.3.0/examples$ sudo pip3 install raptorq
Collecting raptorq
  Using cached https://files.pythonhosted.org/packages/d6/bb/1b988168e61812a4005857441ac07953c4a1124d790ea3e6ba9c05c13756/raptorq-1.3.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-910ays70/raptorq/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-910ays70/raptorq/
```

I've tried this with rustc stable 1.41.1 and rustc nightly 1.43.0 and I'm using python 3.7.5.

After that, I've tried with your 1.2.0 release (When there's a python subfolder) and building with maturin or using .so file it's working perfectly.

**Comment by Lulu300** [comment]
I've managed to make it works. Since I'm new to rust I doesn't know exactly how cargo works but you just have to add some extra args and it works.
For building rust lib and python binary file : 
```SH
lulu@Tsukuyomi:~/raptorq-1.3.0$ cargo build --release --features python
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.16
   Compiling memchr v2.3.3
   Compiling ryu v1.0.2
   Compiling serde v1.0.104
   Compiling lazy_static v1.4.0
   Compiling autocfg v1.0.0
   Compiling itoa v0.4.5
   Compiling regex-syntax v0.6.16
   Compiling version_check v0.9.1
   Compiling libc v0.2.67
   Compiling unindent v0.1.5
   Compiling spin v0.5.2
   Compiling thread_local v1.0.1
   Compiling aho-corasick v0.7.10
   Compiling num-traits v0.2.11
   Compiling quote v1.0.3
   Compiling regex v1.3.4
   Compiling pyo3-derive-backend v0.8.5
   Compiling proc-macro-hack v0.5.11
   Compiling serde_derive v1.0.104
   Compiling inventory-impl v0.1.5
   Compiling ctor v0.1.13
   Compiling ghost v0.1.1
   Compiling pyo3cls v0.8.5
   Compiling paste-impl v0.1.7
   Compiling indoc-impl v0.3.4
   Compiling inventory v0.1.5
   Compiling paste v0.1.7
   Compiling indoc v0.3.4
   Compiling serde_json v1.0.48
   Compiling pyo3 v0.8.5
   Compiling raptorq v1.3.0 (/home/lulu/raptorq-1.3.0)
warning: unnecessary parentheses around block return value
  --> src/matrix.rs:87:9
   |
87 |         (mask - 1)
   |         ^^^^^^^^^^ help: remove these parentheses
   |
   = note: `#[warn(unused_parens)]` on by default

warning: method is never used: `add_new_packet`
  --> src/decoder.rs:83:5
   |
83 |     pub fn add_new_packet(&mut self, packet: EncodingPacket) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: method is never used: `get_result`
  --> src/decoder.rs:90:5
   |
90 |     pub fn get_result(&self) -> Option<Vec<u8>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished release [optimized + debuginfo] target(s) in 1m 41s
```
And if you want to generate python wheels : 
```SH
lulu@Tsukuyomi:~/raptorq-1.3.0$ maturin build --cargo-extra-args="--release --features python"
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
⚠ The are local dependencies, which the source distribution might not include: 
📦 Built source distribution to /home/lulu/raptorq-1.3.0/target/wheels/raptorq-1.3.0.tar.gz
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.16
   Compiling memchr v2.3.3
   Compiling serde v1.0.104
   Compiling ryu v1.0.2
   Compiling lazy_static v1.4.0
   Compiling autocfg v1.0.0
   Compiling itoa v0.4.5
   Compiling regex-syntax v0.6.16
   Compiling unindent v0.1.5
   Compiling version_check v0.9.1
   Compiling libc v0.2.67
   Compiling spin v0.5.2
   Compiling thread_local v1.0.1
   Compiling aho-corasick v0.7.10
   Compiling num-traits v0.2.11
   Compiling quote v1.0.3
   Compiling regex v1.3.4
   Compiling pyo3-derive-backend v0.8.5
   Compiling serde_derive v1.0.104
   Compiling proc-macro-hack v0.5.11
   Compiling ghost v0.1.1
   Compiling inventory-impl v0.1.5
   Compiling ctor v0.1.13
   Compiling pyo3cls v0.8.5
   Compiling paste-impl v0.1.7
   Compiling indoc-impl v0.3.4
   Compiling inventory v0.1.5
   Compiling indoc v0.3.4
   Compiling paste v0.1.7
   Compiling serde_json v1.0.48
   Compiling pyo3 v0.8.5
   Compiling raptorq v1.3.0 (/home/lulu/raptorq-1.3.0)
warning: unnecessary parentheses around block return value==========>  ] 49/50: raptorq                                                                                                                          
  --> src/matrix.rs:87:9
   |
87 |         (mask - 1)
   |         ^^^^^^^^^^ help: remove these parentheses
   |
   = note: `#[warn(unused_parens)]` on by default


warning: method is never used: `add_new_packet`=====================>  ] 49/50: raptorq                                                                                                                          
  --> src/decoder.rs:83:5
   |
83 |     pub fn add_new_packet(&mut self, packet: EncodingPacket) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default


warning: method is never used: `get_result`
  --> src/decoder.rs:90:5
   |
90 |     pub fn get_result(&self) -> Option<Vec<u8>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


    Finished release [optimized + debuginfo] target(s) in 1m 39s
📦 Built wheel for CPython 3.7m to /home/lulu/raptorq-1.3.0/target/wheels/raptorq-1.3.0-cp37-cp37m-manylinux1_x86_64.whl
```
I think it could be a good idea to update the README.md file to add those args and maybe find a way for maturin to automatically add the rights args when building. 
But I still have no clue about why your module on Pypi doesn't works :(

**Comment by cberner** [comment]
I updated the README (https://github.com/cberner/raptorq/pull/52), also the Makefile has several targets for the Python bindings. Can you try that out and let me know if it works?

**Comment by Lulu300** [comment]
It's my bad I didn't check the Makefile, I,ve tried using all the Python targets in the makefile and they all works. Thanks for updating the README !

**Comment by cberner** [comment]
Great!
